// apps/demo/src/widgets/PlaceholderWidget.tsx
import type { PanelApi } from '@widgetstools/dock-manager-core';
import type { PanelConfig } from '@widgetstools/dock-manager-core';

/**
 * Generic placeholder widget for panels without a specific widget type.
 * Shows panel info and demonstrates PanelApi read-only methods.
 */
export function PlaceholderWidget({ api: _api, panel }: { api: PanelApi; panel: PanelConfig }) {
  return (
    <div style={{
      display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
      height: '100%', gap: 8, padding: 20, opacity: 0.5,
    }}>
      <span style={{ fontSize: 14, fontWeight: 500 }}>{panel.title}</span>
      <span style={{ fontSize: 11 }}>Panel ID: {panel.id}</span>
      {panel.widgetType && (
        <span style={{ fontSize: 10, opacity: 0.6 }}>Widget: {panel.widgetType}</span>
      )}
    </div>
  );
}

// apps/angular-demo/src/app/widgets/placeholder-widget.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import type { PanelConfig } from '@widgetstools/dock-manager-core';

/**
 * Generic placeholder widget for panels without a specific widget type.
 * Shows panel info and demonstrates PanelApi read-only methods.
 */
@Component({
  selector: 'app-placeholder-widget',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div style="display:flex;flex-direction:column;align-items:center;justify-content:center;height:100%;gap:8px;padding:20px;opacity:0.5;color:inherit">
      <span style="font-size:14px;font-weight:500">{{ panel?.title }}</span>
      <span style="font-size:11px">Panel ID: {{ panel?.id }}</span>
      @if (panel?.widgetType) {
        <span style="font-size:10px;opacity:0.6">Widget: {{ panel.widgetType }}</span>
      }
    </div>
  `,
})
export class PlaceholderWidgetComponent {
  @Input() api: any;
  @Input() panel!: PanelConfig;
}
